Hook.Add("client.disconnected", "Drones.resetOnDisconnected", function(client)  --Send Original character on disconnect(EXP)
    Networking.Receive("lastcontrolled", function(message, client)
        client.setclientcharacter(message)
    end)
end)